name: AnimalBlender
main: io.github.davidg95.animalblender.AnimalBlender
version: 1.2
commands:
   blend:
      description: Blend animals
      usage: /<command> <animal> <radius>
      permission: animalblender.blend
      permission-message: You do not have permission to use this command